export * from './create-apoderado.use-case';
export * from './asignar-estudiante.use-case';
export * from './get-apoderados-por-estudiante.use-case';
export * from './get-all-apoderados.use-case';
export * from './get-apoderado-by-id.use-case';
export * from './update-apoderado.use-case';
export * from './delete-apoderado.use-case';
export * from './get-estudiantes-por-apoderado.use-case';
export * from './remover-estudiante.use-case';
